/** Real-world Vietnamese CAD phrases (Unicode NFC). */
export const SENTENCES = [
  'Đường dây 22kV',
  'Trạm biến áp',
  'Ống cấp nước',
  'Cao độ',
  'Bản đồ quy hoạch sử dụng đất',
  'Đất trường mầm non',
  'Phường An Bình',
  'Ủy ban nhân dân',
  'Khu dân cư hiện hữu chỉnh trang',
  'Đất cây xanh công viên',
  'Mặt cắt ngang đường',
  'Chỉ giới xây dựng',
  'Hướng tuyến thoát nước mưa',
  'Quận Ninh Kiều, thành phố Cần Thơ',
  'Kỹ thuật hạ tầng',
  'Đất thương mại dịch vụ',
  'Hồ điều hòa',
  'Giao thông đối ngoại',
  'Tỷ lệ 1/2000',
  'Chủ nhiệm đồ án',
  'Mương thoát nước',
  'Nhà văn hóa',
  'Bệnh viện đa khoa',
  'Trường tiểu học Cái Khế',
  'Cầu Ninh Kiều',
] as const;
